### ISSUE TITLE
terratest for azure

### ISSUE THREAD

**Issue by FoSix** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#263]
Write/port tests from AWS repository

### TODO:
- [x] get rid of the `idempotence` switch - make this mandatory
- [x] modify the `plan_apply` action to run `terratest` instead of `terraform` (less steps + parametrisation + no UUID)
- [x] (optional) add UUID generation inside `terratest`?
- [x] get rid of `makefile.sh`
- [ ] ~(optional) one `Makefile` that could take path as a parameter?~
- [x] add tests to modules
- [x] investigate [this issue](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/actions/runs/5587271395/jobs/10216980454#step:3:2555) - a problem with init-cfg.sample.txt being renamed instead of copied when test was run locally
- [ ] ~#292~
